const data = {
  products: [
    {
      name: 'Peter-England Shirt',
      slug: 'p1',
      category: 'shirt',
      image: '/images/p1.jpg',
      price: 120,
      count: 10,
      brand: 'Peter England',
      rating: 4.5,
      description: '100% cotton',
    },
    {
      name: 'Peter-England Shirt',
      slug: 'p2',
      category: 'shirt',
      image: '/images/p2.jpg',
      price: 120,
      count: 10,
      brand: 'Peter England',
      rating: 4.5,
      description: '100% cotton',
    },
    {
      name: 'Peter-England Shirt',
      slug: 'p3',
      category: 'shirt',
      image: '/images/p3.jpg',
      price: 120,
      count: 10,
      brand: 'Peter England',
      rating: 4.5,
      description: '100% cotton',
    },
    {
      name: 'Peter-England Shirt',
      slug: 'p4',
      category: 'shirt',
      image: '/images/p4.jpg',
      price: 120,
      count: 10,
      brand: 'Peter England',
      rating: 4.5,
      description: '100% cotton',
    },
  ],
};
export default data;
